### PR TITLE
Added graphics pipemenu

### PR DESCRIPTION
**Pull request by capn-damo**
Pipemenu for graphics applications, and screenshooter utilities

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Oh, cool!

But `INSTALLED` appears to be unused, right?

**Comment by capn-damo** [comment]
Well-spotted (I think!)

I used the browser pipemenu as a template, and removed the section for
choosing a default browser. Seems that the $INSTALLED flag was needed for
that, so I'll try removing those references.

**Comment by capn-damo** [comment]
I have hard-coded filepaths for the scrot images, which will need to be changed to whatever the default $USER home dir has. "~/Pictures"?

I haven't found a way of using a variable for the path in the menuItem :(

**Comment by ghost** [comment]
https://wiki.archlinux.org/index.php/Xdg_user_directories . If the package xdg-user-dirs is installed, users can set the path for pictures, music and stuff. The package contains a command to query these settings (if you run as a given user), but ATM I'm at Arch so you have to check :)

**Pull request merged**
