### PR TITLE
Add bl-kb-pipemenu, edit bl-help-pipemenu

### PR DESCRIPTION
**Pull request by capn-damo**
bl-kb-pipemenu requires bl-kb.py, so I need a suggestion where to upload that to.

### CODE REVIEW

**Comment by johnraff** [comment]
How about putting  bl-kb.py in bunsen-common, so it will end up in /usr/lib/bunsen/bunsen-common along with bl-include.cfg ? I feel bunsen-utilities is more for things that users will want to use directly, from the menu or keybindings or in their own modifications. No?

**Comment by johnraff** [comment]
True. Anyway it will change soon enough I guess. Let's go with xdg-open for now.

That leaves what to do with  bl-kb.py...

**Comment by capn-damo** [comment]
I missed your earlier comment about bunsen-common/bunsen-utilities, sorry.

From bl-kb.py:
`USAGE: to display keybinds in a text window use 'bl-kb.py --gui'`
`Running the script without args will send output to the terminal`

So it can be used by bl-kb-pipemenu, or as a standalone script to display formatted keybinds in a zenity textinfo window or the terminal. That's why I suggested "bunsen-utilities", rather than bunsen-common.

**Comment by johnraff** [comment]
That would mean that bunsen-utilities became a dependency of bunsen-pipemenus. (bunsen-common already is a dependency.) Adding one more may not be a big issue I suppose - can we imagine some user case where someone might want to install -pipemenus but not -utilities?

**Comment by capn-damo** [comment]
"can we imagine some user case where someone might want to install -pipemenus but not -utilities?"
Very unlikely?

EDIT: just seen you have put up bunsen-utilities. I still think that is the appropriate place

**Comment by johnraff** [comment]
OK let's do it.

BTW I'll have to update the READMEs on -exit, -lock, -user-setup and -wmhacks, so people contribute improvements to -utilities instead. We shouldn't delete the old ones I guess, because they contain comments. Maybe they can be set read-only? I'll have a look.

**Comment by johnraff** [comment]
...just noticed you've added user .cfg files for -multimedia and -graphics. Cool idea! 

Since they're likely to be rather small files, perhaps the pipemenu configs could all be rolled into one pipemenus.cfg? It would mean different names for the arrays though. 

(BTW I've been wondering if .cfg is the right ending for a file containing shell commands? First came up with bl-include.cfg.)

Also, is this line necessary?
`
BL_INCLUDE='/usr/bin' 
`
Anything in /usr/bin will be in $PATH anyway.

**Comment by capn-damo** [comment]
I used cfg because bl-include.cfg was named that way. Maybe "pipemenurc" would do? It's a better idea to include all the pipemenu arrays in a single file I think - it's easy enough to edit in unique array names eg just prepend "GRAPHICS_", "BROWSER_" etc. - there aren't many to do.

I can't remember why that BL_INCLUDE line is there!

**Comment by johnraff** [comment]
Or perhaps add the dot for readability? ie pipemenu.rc (and bl-include.rc). 
Geany applies a certain highlighting for .cfg files... and the same one for .rc files! So maybe there's nothing to be gained by changing. 
Unix file naming conventions seem pretty loose.

**Pull request merged**
