### PR TITLE
Adapt new Debian source package format, fixing incompliances on the way

### PR DESCRIPTION
**Pull request by ghost**
- Adapt current Debian source package format, remove DEBIAN directory
- Fix invalid file format in debian/copyright
- Fix invalid file format in debian/changelog
- Update sections in debian/control
- Create README.Debian with old notes split out from debian/copyright

@johnraff , I'm doing this via pull request so that we can review the changes. I have converted the package to the current/common Debian source package format based on debhelpers. I had to change the format or structure of some files as I went since they were not compliant with the build process. What do you think?

PS. It seems like you did edit debian/changelog manually, producing invalid changelog entries. For updating the changelog, 'dch' is usually used. If you set EDITOR=vim (or emacs), and active syntax highlighting, vim at least will highlight syntax errors.

### CODE REVIEW

**Comment by johnraff** [comment]
@2ion Thank you for your work. I quite agree about following the current standards.

**Comment by Sector11** [comment]
@2ion - good stuff.  A question about the pipemenu ... Is it Compositor or Compton?
I see: R bl-compositor (0)
or is that just a generic term?

**Comment by ghost** [comment]
compton is an implementation of a X11 compositor -- so yes, it's the generic term for what the software does.

**Comment by Sector11** [comment]
Thank you.

**Pull request merged**
