### PR TITLE
bl-multimedia-pipemenu

### PR DESCRIPTION
**Pull request by capn-damo**
Players: 
vlc, mpv, audacious, smplayer

Editors (set in bl-mmeditors-pipemenu):
mhwaveedit, audacity, openshot

Utilities (set in bl-mmutils-pipemenu):
xfburn, gtk-recordmydesktop, volti-mixer

### CODE REVIEW

**Comment by Sector11** [comment]
Does this pipmenu add the "deb-multimedia repo" as well?

**Comment by ghost** [comment]
@Sector11 No it doesn't, we would need to place an appropriatea APT source file in /etc/apt/sources.list.d. The question is whether this package is the right place to add that file. IMHO it's not. We should do this, if anywhere, in bunsen-netinstall.

More important: Was there a consensus about enabling the multimedia repo or any discussion at all? Would it be worth adding the repo just for one program?

**Comment by capn-damo** [comment]
I put deadbeef in there because it is popular - it's easy enough to take it out after all :)

I was thinking of raising the idea of including debian multimedia or deb-multimedia in apt, maybe with a note in sources.list that it could be activated.

**Comment by Sector11** [comment]
@ 2ion  I think that's my point.  I had the debian-multimedia years ago with Ubu ... and for the first few years with #! ... have not had it for a long time and "on my system" tweaking it out of the "sources" would be one of my first priorities.  People see to like audacious for a default (I'll not vote I don't use one) and it's in the regular repos.

Mind you - I'll go with the flow.  My views are those of a "user" as I have no skills to do what's going on here.

**Comment by ghost** [comment]
On Thu, Apr 02, 2015 at 12:24:27PM -0700, damo wrote:

> I put deadbeef in there because it is popular - it's easy enough to take it out
> after all :)

...says who? :D No, seriously. First time I've ever heard of it.

> I was thinking of raising the idea of including debian multimedia or
> deb-multimedia in apt, maybe with a note in sources.list that it could be
> activated.

As a file /etc/apt/sources.list.d/deb-multimedia.list with the ^deb line
commented out! Doesn't sound like a bad idea! We should the same for the to-be
jessie backports repository.

**Comment by johnraff** [comment]
I wonder if sources.list might be the better place to put a commented-out deb-multimedia entry? It would be more visible there, and also, the sources.d directory is a handy place for scripts to add (or remove) repositories automatically. 

Opinions vary about deb-multimedia. I use it, but some people say there are issues with some of the packages... I'm not sure if we should be seen to be _recommending_ it? Maybe adding the deb-multimedia repo could be an item in the bl-welcome script? 

Or if someone chose to install deadbeef from the media pipemenu then they could get a warning/prompt that that repo would be added? Alternatively, the pipemenu could check if the repo had been enabled before putting up the deadbeef entry?

**Comment by capn-damo** [comment]
"Or if someone chose to install deadbeef from the media pipemenu then they could get a warning/prompt that that repo would be added"

That was the way I was thinking it could be dealt with.

But having used audacious for a few days, I find it is very similar to deadbeef so I wouldn't object if it was dropped from the menu. 

I still think a deb-multimedia option should be included though

**Comment by Sector11** [comment]
I'll just leave this here: [Remove unofficial debian-multimedia.org repository from your sources](https://bits.debian.org/2013/06/remove-debian-multimedia.html)

and this: [on package duplication between Debian and debian-multimedia](http://lists.alioth.debian.org/pipermail/pkg-multimedia-maintainers/2012-May/026678.html) which is the link found at deb-multimedia

**Comment by capn-damo** [comment]
debian-multimedia is not the same as deb-multimedia

The original debian-multimedia was asked by Debian to change its name (see deb-multimedia.org, which is what I use), then it seems someone else grabbed the name.

**Comment by Sector11** [comment]
Well, you know me: OOPS! {blush}  size nine boot in a size six mouth --- and make it fit.
As I said: I'll go with the flow, I can't do what you guys are doing.

**Comment by johnraff** [comment]
So perhaps an option to add deb-multi in bl-welcome would be the way to go?

**Comment by capn-damo** [comment]
A choice in bl-welcome seems to me to be the best solution - it could include some explanatory text as well

**Comment by capn-damo** [comment]
I removed the deadbeef option until there is consensus about multimedia repos.

**Pull request merged**
