### PR TITLE
Added test for 'xdg-user-dir PICTURES'; now using vars for filepaths in writeScrot()

### PR DESCRIPTION
**Pull request by capn-damo**

### CODE REVIEW

**Comment by ghost** [comment]
It'd be better to test for xdg-user-dir with

```
type xdg-user-dir &>/dev/null
```

IMHO

**Comment by AlexDaniel** [comment]
@2ion, yeah, I agree.

**Comment by johnraff** [comment]
Not sure if this will work:

```
 VIEW="'viewnior $IMG'"
```

The single quotes need to be removed.

**Comment by Sector11** [comment]
Also, it has been decide that "mirage" will be the default image viewer in BunsenLabs

**Comment by capn-damo** [comment]
@johnraff 
That was the only way I found to get it to work. The scrot command in the xml needs to be quoted properly, but I freely admit I find it hard to get my head around quoting in bash :(

It expands to
`<command>
                    scrot /home/damo/images/%F-%H-%M_scrot.png -e &apos;viewnior /home/damo/images/%F-%H-%M_scrot.png&apos;
</command>`

@Bruce
Mirage - glad to hear it will be default. It is what I use :)

**Comment by Sector11** [comment]
Is this what you mean damo?
In OpenBox:

Label: View M
Command: mirage ~/images

Scrots
Label: Now
Command: scrot '%F_%T_$wx$h_Sector11.png' -e 'mv $f ~/images/ ; mirage ~/images/$f'

[box] or a [window]
Label: [png]
Command: scrot -s '%F_%T_$wx$h_Sector11.png' -e 'mv $f ~/images/ ; mirage ~/images/$f'

Timed:
Label: 05
Command: scrot -d 5 '%F_%T_$wx$h_Sector11.jpg' -e 'mv $f ~/images/ ; mirage ~/images/$f'

%T = 24hour time

Full screen: = ~/images/2015-03-19_11:18:25_1920x1080_Sector11.png

[.png] = ~/images/2015-03-19_11:27:27_600x428_Sector11.png

**Comment by Sector11** [comment]
OOPS  How do I open it?

**Comment by capn-damo** [comment]
@Sector11 

Not sure what you mean there Bruce?

If you run "bl-graphics-pipemenu" as a command in a terminal (or any other pipemenu for that matter), then the xml is echoed to the screen, just as it would appear if it was written in menu.xml AFAICS

I can never see why the screenshot should be made in ~/, then moved somewhere else. Just save it in the images directory to start with!

**Pull request merged**
